# configuration for "master" branch
-
  branches:
    only:
      - master
  configuration: Release
  platform: Any CPU
  skip_tags: true
  image: Visual Studio 2015
  version: 1.0.{build}
  pull_requests:
    do_not_increment_build_number: true
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true
  environment:
    COVERALLS_REPO_TOKEN:
      secure: <the encrypted key>
  build:
    parallel: true
    project: Picton.Common.sln
    publish_nuget: true
    verbosity: minimal
  before_build:
    - nuget restore
  test_script:
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"vstest.console.exe" -targetargs:"/logger:Appveyor ""Picton.Common.UnitTests\bin\%configuration%\Picton.Common.UnitTests.dll""" -filter:"+[Picton.Common]* -[Picton.]Picton.Common.Properties.*" -excludebyattribute:"*.ExcludeFromCodeCoverage*" -hideskipped:"All" -output:coverage.xml
  after_test: 
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  notifications:
    - provider: Email
      to:
      - desautelsj@hotmail.com
      subject: Picton.Common Build
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: false
  deploy:
    provider: NuGet
    api_key:
      secure: <the encrypted key>
    artifact: /.*\.nupkg/
    appveyor_repo_tag: true


# "fall back" configuration for all other branches
# no "branches" section defined
-
  configuration: Release
  platform: Any CPU
  skip_tags: true
  image: Visual Studio 2015
  version: 1.0.{build}-pre
  pull_requests:
    do_not_increment_build_number: true
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true
  environment:
    COVERALLS_REPO_TOKEN:
      secure: <the encrypted key>
  build:
    parallel: true
    project: Picton.Common.sln
    publish_nuget: true
    verbosity: minimal
  before_build:
    - nuget restore
  test_script:
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"vstest.console.exe" -targetargs:"/logger:Appveyor ""Picton.Common.UnitTests\bin\%configuration%\Picton.Common.UnitTests.dll""" -filter:"+[Picton.Common]* -[Picton.Common]Picton.Common.Models.* -[Picton.Common]Picton.Common.Properties.*" -excludebyattribute:"*.ExcludeFromCodeCoverage*" -hideskipped:"All" -output:coverage.xml
  after_test: 
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  notifications:
    - provider: Email
      to:
      - desautelsj@hotmail.com
      subject: Picton.Common Build
      on_build_success: false
      on_build_failure: false
      on_build_status_changed: true
