# Build script
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor"

# Tests
test: off

# Build cache
cache:
- packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
- tools -> build.cake, tools\packages.config
